import {
  Activity,
  Bell,
  BookOpenText,
  Boxes,
  Coins,
  Download,
  Home,
  History,
  Image,
  KeyRound,
  Layers3,
  Mail,
  Settings,
  ShieldCheck,
  Video,
  Package,
  Users,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const studioRoutePaths = {
  adminSettings: '/admin/settings',
  adminUsers: '/admin/users',
  accountSettings: '/account/settings',
  assetsGraph: '/assets-graph',
  gallery: '/gallery',
  home: '/',
  mySessions: '/account/sessions',
  notifications: '/notifications',
  organizationInvitations: '/admin/invitations',
  queue: '/queue',
  shortVideo: '/short-video',
  storyAnalysis: '/story-analysis',
  storyboard: '/storyboard',
  timelineExport: '/timeline-export',
  wallet: '/wallet',
  transactions: '/transactions',
  workerMetrics: '/admin/worker-metrics',
  workspaces: '/workspaces',
} as const

export type StudioNavItem = {
  description: string
  disabled?: boolean
  group: 'account' | 'admin' | 'creation' | 'operations'
  icon: LucideIcon
  key: keyof typeof studioRoutePaths
  label: string
  path: string
}

export const studioNavItems: StudioNavItem[] = [
  {
    description: '项目总览、生产信号和页面跳转入口。',
    group: 'creation',
    icon: Home,
    key: 'home',
    label: '导演台首页',
    path: studioRoutePaths.home,
  },
  {
    description: '录入故事源、启动多智能体解析并查看结果。',
    group: 'creation',
    icon: BookOpenText,
    key: 'storyAnalysis',
    label: '故事解析',
    path: studioRoutePaths.storyAnalysis,
  },
  {
    description: '管理分镜卡、提示词和镜头级审批动作。',
    group: 'creation',
    icon: Boxes,
    key: 'storyboard',
    label: '分镜台',
    path: studioRoutePaths.storyboard,
  },
  {
    description: '浏览故事图谱、候选资产并锁定参考素材。',
    group: 'creation',
    icon: Layers3,
    key: 'assetsGraph',
    label: '资产图谱',
    path: studioRoutePaths.assetsGraph,
  },
  {
    description: '网格视图浏览所有生成的素材，支持类型和状态筛选。',
    group: 'creation',
    icon: Image,
    key: 'gallery',
    label: '素材库',
    path: studioRoutePaths.gallery,
  },
  {
    description: 'AI 生成电商短视频，支持多种模板和自定义参数。',
    group: 'creation',
    icon: Video,
    key: 'shortVideo',
    label: '电商短视频',
    path: studioRoutePaths.shortVideo,
  },
  {
    description: '浏览团队工作空间，查看工作空间信息。',
    group: 'operations',
    icon: Package,
    key: 'workspaces',
    label: '工作区',
    path: studioRoutePaths.workspaces,
  },
  {
    description: '实时监控所有生成任务的进度和状态。',
    group: 'creation',
    icon: Activity,
    key: 'queue',
    label: '生成队列',
    path: studioRoutePaths.queue,
  },
  {
    description: '编排时间线、保存剪辑并发起导出。',
    group: 'creation',
    icon: Download,
    key: 'timelineExport',
    label: '时间线导出',
    path: studioRoutePaths.timelineExport,
  },
  {
    description: '管理 AI 端点配置和积分设置。',
    group: 'admin',
    icon: Settings,
    key: 'adminSettings',
    label: '系统设置',
    path: studioRoutePaths.adminSettings,
  },
  {
    description: '查看组织成员、角色和最近活跃时间。',
    group: 'admin',
    icon: Users,
    key: 'adminUsers',
    label: '用户管理',
    path: studioRoutePaths.adminUsers,
  },
  {
    description: '为协作者签发组织邀请（owner / admin）。',
    group: 'admin',
    icon: Mail,
    key: 'organizationInvitations',
    label: '邀请管理',
    path: studioRoutePaths.organizationInvitations,
  },
  {
    description: '修改密码并管理个人 API Key 自动化凭证。',
    group: 'account',
    icon: ShieldCheck,
    key: 'accountSettings',
    label: '账号设置',
    path: studioRoutePaths.accountSettings,
  },
  {
    description: '查看并吊销当前账号的登录会话。',
    group: 'account',
    icon: KeyRound,
    key: 'mySessions',
    label: '登录会话',
    path: studioRoutePaths.mySessions,
  },
  {
    description: '查看积分余额、充值/扣费流水（owner / admin 可调整）。',
    group: 'operations',
    icon: Coins,
    key: 'wallet',
    label: '钱包中心',
    path: studioRoutePaths.wallet,
  },
  {
    description: '查看完整的交易历史和流水明细。',
    group: 'operations',
    icon: History,
    key: 'transactions',
    label: '交易流水',
    path: studioRoutePaths.transactions,
  },
  {
    description: '查看系统通知：钱包操作、邀请、配置变更。',
    group: 'operations',
    icon: Bell,
    key: 'notifications',
    label: '通知中心',
    path: studioRoutePaths.notifications,
  },
  {
    description: '查看 worker 组织上下文跳过指标（owner / admin）。',
    group: 'admin',
    icon: Activity,
    key: 'workerMetrics',
    label: '执行器指标',
    path: studioRoutePaths.workerMetrics,
  },
]
